### PR TITLE
Highlights - Programmatic add/removal of highlights

### PR DESCRIPTION
**Pull request by kulny**
This pull enables adding highlights programmatically, and also introduces some helper methods to make managing HighlightM objects easier. Additionally, the ability to programmatically remove arbitrary sections of a highlight (and have the highlights persist) has been added.

### CODE REVIEW

**Comment by kulny** [comment]
One thing to be aware of, though I'm not sure if it's an issue or even matters at all, is that the majority of the tests here functionally test two things: 

1. EditorController's interactions with HighlightsState
2. That the methods in HighlightsState work as expected. 

This is notable because it means that there are some functions in HighlightsState that don't have a way to be tested without providing access to them from EditorController - or alternatively creating a new set of tests specifically for HighlightsState. I am not going to do that here because I don't want to bog down the purpose of this PR with separate tasks.

If creating tests specifically for HighlightsState were to be needed in addition, it should be as simple as creating a HighlightsState object and passing each method expected information. As far as I can tell, it won't need much in terms of mock information.

**Comment by adrian-moisa** [comment]
I had a tough time lately finding time. There's a lot to do in the backlog and the dayjob was rather demanding lately. I'll review carefully these days the commit to see what can be improved. Expect more feedback.

**Comment by kulny** [comment]
@adrian-moisa I believe this PR is ready to be considered for merge, however there are some fundamental API differences that I am unsure if there are ways around. For example, the `highlights` value given to `EditorController` seems like it cannot be directly provided because we need to ensure the list is not const, which would preclude dynamically adding highlights. I've also added a getter which directly accesses the `_state` value of `EditorController`.

I believe the test coverage is comprehensive for the changes made, but let me know if there are any missing.

**Comment by adrian-moisa** [comment]
Oh wow, I was just looking trough the prev Commit to better understand your intentions. I'm currently adding a method to add highlights from the controller. There were some issues regarding updating the layout on demand. I used safeMarkNeedsPaint(). I'll be pushing soon. Have a look on the last commit to see how it was done. 

I suggest when you have some time let's meet on discord so we can compare notes. Also please do a rebase, seems like right now we have conflicts. Cheers!

PS I think you'll have to cherrypick. Something looks very odd in the commit. It looks like you are trying to add code that I already added. 

PS2 --> I've also added a getter which directly accesses the _state value of EditorController. --> I made special effort not to allow access to the state. You are breaking encapsulation, thus allowing anyone to write code that depends on our private code. Therefore our private code becomes public API, therefore we can't safely upgrade without ruining many client apps that used the private state for their own affairs.


Straight from the docs:

## Encapsulation
A major concern when designing the state store was to make sure that the state store is not exposed in the public. Encapsulating the state prevents developers from accessing/changing the internal state when writing client code. Preventing such practices enables the library source code to evolve  without introducing breaking changes in the client code.

There are many classes that need the state to be passed around. An additional challenge is that we need multiple state store, one per `EditorController` instance. Otherwise we end up having several editors in the same page that share the same state. The first attempt to migrate the state architecture made use of singleton classes to store the state per features. However once complete the issue of sharing states between running instances showed up. The solution was to bundle all the state classes in a single `EditorState` class. This class gets instantiated once per `EditorController`. Therefore each editor instance has it's own internal state independent of the other editors from the same page.

**Passing State**

Methods hosted in services receive the state via params. As explained above we can't inject in services the state if we want multiple editors on the same page. So some amount of prop drilling is present in the code base. However for widgets the things are looking better. We pass to the widgets/controllers/renderers the editor state via the constructor's params. A public-write-only setter is used to prevent access to the state from the outside.

```dart
class ColorButton extends StatefulWidget with EditorStateReceiver {
  late EditorState _state;

  @override
  void setState(EditorState state) {
    _state = state;
  }
```

**Comment by kulny** [comment]
For some reason when I try to rebase it does rebase, but won't actually clear all of the conflicts after I manage them. I had, in fact, already attempted a rebase when you posted your comment, however I seem to not understand how the rebasing works well enough to solve the issue. 

I have changed my method of accessing the highlights to be a method `getHighlights()` similar to the way in which you have provided access to Markers. The logic used to access the highlights is exactly the same, however it is simply not a getter. 

```dart
  List<HighlightM> getHighlights() {
    return _state.highlights.highlights;
  }
```

I will continue trying to figure out how to properly rebase my changes on the newest branches, however depending on whether I can get it to rebase properly, I may end up closing this PR and cherry picking my changes into a new PR.

**Comment by kulny** [comment]
Alright, I think it's all clean, now. 

The API for retrieving highlights now uses a `getHighlights` method. According to the pull request on my editor, there are no conflicts, however github itself is still showing that there are conflicts. I'm not sure what the issue is with that. 

If I am still missing something, I would appreciate any guidance you could give.

**Comment by adrian-moisa** [comment]
Closed for now, too many conflicts. Also the changes could have been implemented externally in the client code. Most of the extensions seem to duplicate existing features. Let's debate in an audio meeting.

**Pull request closed without merging**
